export enum Events {
    UPDATING_COMMAND_STATE = 'UPDATING_COMMAND_STATE',
    NEW_COMMAND_STATE = 'NEW_COMMAND_STATE',
    TICK_UPDATE = 'TICK_UPDATE',
    CONFIG_ADDED = 'CONFIG_ADDED',
    CONFIG_UPDATED = 'CONFIG_UPDATED',
    SHOW_TIME_SELECTION = 'SHOW_TIME_SELECTION',
    TIME_SELECTED = 'TIME_SELECTED',
    RESET_TIME_TO_UPDATE = ''
}